### ISSUE TITLE
Client logging in addition to server logging

### ISSUE THREAD

**Issue by mitchtbaum** [foundpatterns/lighttouch-logging#2]
|  *   server    *    * |  *   client    * |
incoming request + outgoing response | outgoing request + incoming response

**Comment by mitchtbaum** [comment]
```
log/in-request/
log/out-response/
log/out-request/
log/in-response/
log/torchbear/
```

**Comment by Arnaz87** [comment]
The solution I see is to make a binding in lithttouch to the torchbear's binding to the actix's ClientRequestBuilder, and implement the logging in that lighttouch binding.

**Comment by Arnaz87** [comment]
I don't know what name it should have but the wrapper function would accept three parameters: method, uri and request (which has headers and body) and use that to build the request.

I think this should be the behaviour of the lighttouch binding to begin with.

**Comment by Arnaz87** [comment]
alternatively just one request parameter, with the uri and method in it. I think I like this one better

**Comment by Arnaz87** [comment]
example request:

~~~lua
send_request({
  uri="localhost:3000",
  method="post",
  headers={
    ["content-type"]="application/json"
  },
  body='{"msg":"Hello World"}'
})
~~~

**Comment by Arnaz87** [comment]
The lighttouch wrapper would be something like this:
~~~
function lighttouch_send_request (request)
log_outgoing_request(request)
local response = send_request(request)
log_incoming_response(response)
return response
end
~~~

**Comment by Arnaz87** [comment]
This function should be in lighttouch-logging because it extends with logging functionality

**Comment by Arnaz87** [comment]
if it should be an event instead of a helper function
~~~lua
log_outgoing_request(request)
~~~
Becomes
~~~lua
events["log_outgoing_request"]:trigger("request")
~~~

**Comment by mitchtbaum** [comment]
outgoing_request

**Comment by mitchtbaum** [comment]
## events
before: incoming request received, outgoing response about to be sent
now: outgoing request about to be sent, incoming response received

**Comment by Arnaz87** [comment]
If [this](https://github.com/foundpatterns/lighttouch-libs/issues/20#issue-369986322) is closed, `log_outgoing_request` will be an event, otherwise it has to be a helper function

**Comment by mitchtbaum** [comment]
This new send_request() wrapper from torchbear web client bindings provides logging and syntax improvement

**Comment by mitchtbaum** [comment]
this is relevant to to Rust's web client bindings

..I'm trying to make a plan that shows related changes

**Comment by mitchtbaum** [comment]
https://github.com/foundpatterns/lighttouch-logging/commit/dc18cc5c2b62fef861c26bbda751ae4f75393c71

**Comment by mitchtbaum** [comment]
https://github.com/foundpatterns/lighttouch-base/commit/9cb9ba5d6ee1d9968a55439425f452249ca4abf9
