### ISSUE TITLE
Fix workaround for logging outgoing request and incomming response

### ISSUE THREAD

**Issue by Arnaz87** [foundpatterns/lighttouch-logging#4]
[helpers.send_request](https://github.com/foundpatterns/lighttouch-logging/blob/76d9f7ed17ed9e127dd0e94a90a588c80b564329/helpers.lua#L6) isn't supposed to be a helper function but a lighttouch-libs function, and the logging functionality [here](https://github.com/foundpatterns/lighttouch-logging/blob/76d9f7ed17ed9e127dd0e94a90a588c80b564329/helpers.lua#L9-L25) and [here](https://github.com/foundpatterns/lighttouch-logging/blob/76d9f7ed17ed9e127dd0e94a90a588c80b564329/helpers.lua#L30-L41) are supposed to be actions fired on `outgoing_request` and `incoming_response` events.

**Comment by mitchtbaum** [comment]
https://github.com/foundpatterns/lighttouch-logging/commit/dc18cc5c2b62fef861c26bbda751ae4f75393c71
